name: Streamlit app actions
on: [push, pull_request]
jobs:
  streamlit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: streamlit/streamlit-app-action@198c0451ff2e9f60b380f7d21b046f63600e365c
        with:
          app-path: Chatbot.py
